# Generated by Django 2.2.7 on 2019-11-22 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machineries', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on wich the object was last modified.', verbose_name='modified at')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the object is active or not', verbose_name='is active')),
                ('elimination_reason', models.CharField(blank=True, help_text='Indicates the reason for removing the object', max_length=255, null=True, verbose_name='elimination reason')),
                ('rental_amount', models.FloatField(default=0.0, help_text='The amount for the rental of the specified machinery')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('rental_address', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.Client')),
                ('machinery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machineries.Machinery')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
