# Generated by Django 2.2.7 on 2019-11-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0002_rental_rented_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='code',
            field=models.SlugField(unique=True),
            preserve_default=False,
        ),
    ]
